//! Raw FFI bindings to llama.cpp (llama.h), gguf.h and mtmd.h.
//! Generated by bindgen at build time from the local llama.cpp checkout.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(deprecated)]
#![allow(clippy::missing_safety_doc)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
